### ISSUE TITLE
Create simpler example or add comments

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/Dogify#1]
Could you add comments for which parts are injected and what data is being consumed?

Or, create a simpler example where a single data source is consumed by the Android/iOS app?

**Comment by seabornlee** [comment]
The domain layer (Usecase) and data layer (Repository) are shared, Android and iOS have their own ViewModels which consume Usecases.
You can start looking at `MainViewModel`.

Folder structure:
`androidApp` - Android specific code, including View and ViewModel. Can be Kotlin and Java.
`iosApp` - iOS specific code, including View and ViewModel. Can be Swift and OC.
`shared/commonMain` - The shared code. Business logic and data layer. If some code depends on the platform such as Database driver in this project, then we can use Kotlin keyword `expect` to define `interface` and provide `implementation` with Kotlin keyword `actual` in `shared/src/androidMain` or `iosMain`.

@JamesSmartCell @hboon
